### ISSUE TITLE
Create common Exception interface, break exceptions into smaller parts

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#10]
It is a common practice to introduce a generic Exception interface so that all exceptions thrown by this library can be caught in a single catch.

Also, as discussed on gitter, we should create more exceptions instead of one or two big ones.

**Comment by ddeboer** [comment]
:+1:

At least differentiate between client exceptions (400s), server exceptions (500s) and networking errors (timeouts and such).

**Comment by sagikazarmark** [comment]
That's a good point.

Currently the separation is based on single and multi requests.

Can you open a separate issue for that?
