### ISSUE TITLE
People get the idea?

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#100]
Is it just me or people really don't get the idea behind httplug?

This is just one example:

https://github.com/toin0u/DigitalOceanV2/issues/75#issuecomment-166371056

**Comment by dbu** [comment]
i guess we need to have patience and be very clear in explaining that
httplug is not another client, but a client abstraction layer so that
libraries do not need to write their own layer, or tie themselves to a
specific client implementation.

**Comment by sagikazarmark** [comment]
There are a few arguments which are totally acceptable in my opinion: not being stable, messy documentation, etc.

But people **claiming** to understand what HTTPlug is are being reluctant about using it and mention arguments which are either not true or reflect that they actually don't get the idea behind.

Wonder if it would be different if it was a PSR.

**Comment by dbu** [comment]
i am sure it being a PSR would make people get the correct assumption.

**Comment by Nyholm** [comment]
Sure it would be different with a PSR but that is far from the only solution. The situation is that every api client uses at least one http client. If it is a well built library (api client) they have adapters for Guzzle5 and 6 etc. 

What we need to do is to explain why the current situation is a bad idea. But not in terms on "more code", "hard to maintain", "keep up with changes in guzzle" etc. I think we need to be more clever than that. Let's put on the hat of data scientist and explain that current situation violates the _common reuse principle_, _dependency inversion principle_ and by doing adapters yourself you risk violating the _liskov substitution principle_ etc etc. I do also believe that we need to show package dependencies in a graph/images. 

The message we want to send is: "You focus on your api, we focus on the transportation of data. Trust us, we know our shit."

> There are a few arguments which are totally acceptable in my opinion: not being stable, messy documentation, etc.

I believe these are signs for that developers do not trust us.

**Comment by sagikazarmark** [comment]
Nice summarizing @Nyholm

**Comment by ddeboer** [comment]
Yes, good summary. In our docs, we should answer the questions:
- Why should my library/framework depend on Httplug instead of a concrete HTTP client? Answer: everything mentioned by @Nyholm – in one word: decoupling.
- What do I gain by using Httplug? Answer: you can stop worrying about supporting any concrete clients.

**Comment by ddeboer** [comment]
Documentation has improved a lot over the last couple of days. Please have a look at http://php-http.readthedocs.org/en/latest/ and let me know what we can do to make them even clearer.

**Comment by sagikazarmark** [comment]
I had an idea to create a two-step migration process: php-http/documentation#57

The idea is that you can use HTTPlug API internally without breaking BC at first.

**Comment by sagikazarmark** [comment]
Let's solve this. :smile:
