### ISSUE TITLE
Repository/package cleanup

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#101]
Now, that we are merging repositories together, the question comes up whether we should remove the deprecated repositories or not.

Pros:
- less repository, less confusion
- less repository, less maintenance

Cons:
- some of the repositories have already been tagged, which means they COULD be used somewhere. Fortunately packagist gives us information about dependent packages.
- we lose issues, PRs, history (which is probably not a big deal in the current phase of the project)

**Comment by dbu** [comment]
i propose we mark all repositories we don't need anymore as abandoned on
packagist and explain that they are fading out and where the content
moved. one month after tagging 1.0, we can remove them. that gives
people some time to update.

**Comment by sagikazarmark** [comment]
> i propose we mark all repositories we don't need anymore as abandoned on packagist

Already done.

> explain that they are fading out and where the content moved

Also done. Marked as deprecated, moved to repository text is in the beginning of the README.

> one month after tagging 1.0, we can remove them. that gives people some time to update.

Sounds good to me.

**Comment by joelwurtz** [comment]
:+1:

**Comment by ddeboer** [comment]
Shouldn’t [php-http/adapter](https://packagist.org/packages/php-http/adapter) be marked deprecated in favour of httplug?

**Comment by sagikazarmark** [comment]
It should be. The repo itself is already removed I think, the package should also be deleted at some point.

**Comment by dbu** [comment]
the repo already redirects. i suggest we delete it from packagist (if
that is possible nowadays, i think it used to be impossible to delete
things)

**Comment by sagikazarmark** [comment]
@Seldaek Can you please delete php-http/adapter package from packagist?

**Comment by Seldaek** [comment]
I can, but it's still being downloaded a bit https://packagist.org/packages/php-http/adapter/stats so I think it's best to wait a few more weeks/months to make sure everyone has time to get the abandon warning and move over. Just ping me again here in a bit?

**Comment by sagikazarmark** [comment]
Thanks for the reply. I will contact the package authors who still rely on the old package.

**Comment by sagikazarmark** [comment]
Oops, one of our packages rely on the old package.

**Comment by ddeboer** [comment]
Lol, package overflow confusion. :wink:

**Comment by joelwurtz** [comment]
Can we begin to clear some deprecated packages ? Would be nice to have something clean for the first release

**Comment by sagikazarmark** [comment]
Yes.

@Seldaek regardless of the installation count, can you please remove php-http/adapter?

Please also remove the following packages:
- php-http/encoding
- php-http/authentication
- php-http/cookie
- php-http/client-tools

Also, package authors please update your packages and remove dependency on the following:

[php-http/utils](https://packagist.org/packages/php-http/utils/dependents): @mekras, @lanthaler, @swader
[php-http/message-decorator](https://packagist.org/packages/php-http/message-decorator/dependents): @dbu, @ddeboer

**Comment by Seldaek** [comment]
Done

**Comment by sagikazarmark** [comment]
Thank you very much.

**Comment by dbu** [comment]
thanks.

@sagikazarmark i rebased an older PR that was lying around. i think that was the reason for this dependency - in master we no longer depend on it.

**Comment by sagikazarmark** [comment]
Ok. @Seldaek can you please delete php-http/message-decorator as well? Thank you very much.

We only have utils then.

**Comment by Seldaek** [comment]
Alrighty

**Comment by sagikazarmark** [comment]
Thank you

**Comment by sagikazarmark** [comment]
WOW:

https://packagist.org/packages/php-http/promise/dependents

While client-tools does not exist anymore.

**Comment by Seldaek** [comment]
That's called caching :) It'll go away by tomorrow.

**Comment by sagikazarmark** [comment]
kk, thanks

**Comment by lanthaler** [comment]
> Also, package authors please update your packages and remove dependency on the following:
> 
> php-http/utils

Sure @sagikazarmark. Is there a replacement for it? I think I used it for the Guzzle Message/Stream factories

**Comment by joelwurtz** [comment]
yes there is https://github.com/php-http/message

**Comment by lanthaler** [comment]
Done. The dependency graph is getting bigger and bigger :-(

**Comment by Swader** [comment]
> Done. The dependency graph is getting bigger and bigger :-(

^ this. :(

I, too, have now updated my client and all seems to be working well.

**Comment by sagikazarmark** [comment]
How is it getting bigger? You replaced on package with another.

**Comment by Swader** [comment]
For me in particular, through puli - I do love the package, but it's a rather enormous beast to depend on. The beta status of the composer plugin doesn't help things, either.

**Comment by sagikazarmark** [comment]
I think all packages without dependencies are now cleaned up. All the remaining repositories have dependencies.
