### ISSUE TITLE
Testing on appveyor

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#106]
It seems to be the new trend to test under windows as well?

Do we want to do that?

IMO this is not about testing the code, but testing if our code works on Windows (which is a shame, isn't it? Looking at you Microsoft)

**Comment by dbu** [comment]
it would be good if that works, so if its free and not a big hassle,
lets do it. is that a replacement for travisci? or an addition?

**Comment by sagikazarmark** [comment]
Definitely not a replacement. I don't like Windows, so I rather take it as a confirmation to Windows users that this code works on windows rather than our CI of choice.

**Comment by joelwurtz** [comment]
@dbu appveyor only work on windows platform (it's purpose is mainly for .NET application). For me we shouldn't bother with that, in my experience i have learned that, most of the time, windows developer for PHP are not developer who cares about php-http and the stuff around composer / psr etc ...

**Comment by dbu** [comment]
okay. well, if somebody wants to work on it i am not against it.
not all windows users have no clue and ignore reusable components - the
main dev of composer, jordi, is working on a windows machine ;-)
but i don't plan to spend time on it.

**Comment by sagikazarmark** [comment]
for now, me neither.

let's keep it in the queue with a low prio
