### ISSUE TITLE
Require php 5.3

### ISSUE THREAD

**Issue by ParisLiakos** [php-http/httplug#111]
I dont get why this package requires php 5.4.
It should require 5.3 like all other psr packages

I need this package in a project, but i ended up using something custom because the server was running on php 5.3.10

**Comment by sagikazarmark** [comment]
I don't know why the FIG still supports PHP 5.3. Personally, I think we should not encourage people to use legacy stuff.

However, in this case there is a bigger problem: we use [callable typehints](https://github.com/php-http/promise/blob/master/src/Promise.php#L44) in promise, which is from 5.4.

What you can do is installing composer dependencies with `--ignore-platform-reqs` switch. This will ignore any PHP version or extension requirements.

Sorry I couldn't help. :cry:

**Comment by dbu** [comment]
you should really update your servers. php 5.3 is now totally out of
live, there are not even security updates anymore.

**Comment by ParisLiakos** [comment]
ah, i didnt see the callable typehint. in that case the requirement is valid.
thanks!

@dbu yes, i know, but it in real life you have to work on older projects hosted on a bit outdated servers where you have no power on the php version they use.
