### ISSUE TITLE
alpha or stable stability

### ISSUE THREAD

**Issue by fago** [php-http/httplug#112]
A stable 1.0 release was tagged, but thttp://httplug.io/ says:

> Note: We are currently in the phase of alpha releases. Contributions are very welcome!

So who is wrong? I guess the website needs an update?

**Comment by sagikazarmark** [comment]
Yes, the website needs update, thanks for pointing that.

**Comment by sagikazarmark** [comment]
Closed in https://github.com/php-http/httplug.github.io/commit/89d33b08a487fb73845c44062ba7a765ed8a9e2f
