### ISSUE TITLE
Streams Support?

### ISSUE THREAD

**Issue by irazasyed** [php-http/httplug#114]
Hi,

I'd like to know, Does this project support Streams out of the box? It doesn't look like but wanted to confirm.

I currently use Guzzle for one of my projects but I'd like to move to this one, So it can give more choices to our end users and decouple the HTTP layer.

I did start implementing this library, but had trouble with the file uploads part. Since my project uses multipart for file uploads which Guzzle seems to handle it very well, What's the solution for such requirement?

Let me know ASAP. Thanks!

**Comment by sagikazarmark** [comment]
This library uses PSR-7 for the message layer, which comes with streams out-of-the-box.

For multipart stream support see this PR:
https://github.com/php-http/message-factory/pull/30
