### ISSUE TITLE
Circuit Breaker

### ISSUE THREAD

**Issue by B-Galati** [php-http/httplug#125]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

Hello !

What about implementing a [circuit breaker](https://martinfowler.com/bliki/CircuitBreaker.html) feature on top of httplug ? We could have one library that manage circuit breaker feature and use that library in httplug.

It looks like it's something missing from php libraries. I found multiple one but they look non-maintained. 

Thanks for your feedback ;-)

**Comment by Nyholm** [comment]
Hey. That sounds like an great idea for a plugin. Please send a PR and I'll be happy to review it.

**Comment by B-Galati** [comment]
@Nyholm Ok, I'll try !

**Comment by Nyholm** [comment]
Any updates on this?

**Comment by B-Galati** [comment]
I will never have the time to implement this and I now think that it can be better to let a proxy manage that kind of logic (traefik for example)

**Comment by B-Galati** [comment]
[Tolerance](http://tolerance.io/) looks like a great library ;-)

**Comment by joelwurtz** [comment]
Closing this also as this is rather old, we are not opposed to the idea, so if anyone wants to implement it, feel free to do it.
