### ISSUE TITLE
Missing badges

### ISSUE THREAD

**Issue by umpirsky** [php-http/httplug#126]
![screenshot from 2017-06-04 12-30-36](https://cloud.githubusercontent.com/assets/208957/26760785/ad83dbcc-4921-11e7-9ff0-a5b540c8c12f.png)

**Comment by sagikazarmark** [comment]
They are there for me. It might be some rate limit you hit or the requests are taking longer for you. (They are there for me even after cache clear.)

**Comment by umpirsky** [comment]
Works now. :)
