### ISSUE TITLE
How to set timeout for a request while being abstracted from a HttpClient implementation?

### ISSUE THREAD

**Issue by Finesse** [php-http/httplug#131]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 1.1.0

I develop a library which uses HTTPlug for abstracting from a HTTP adapter implementation. It makes HTTP requests using `HttpClient` implementation given by the library user. Some requests don't require timeout while some do. How can I make requests with different timeout (and maybe other settings: deny redirects, SSL check, max read length and so on) staying abstracted from a HTTP adapter implementation?

**Comment by gggeek** [comment]
As a side note: besides the timeout there are many more options that can affect the http calls made: usage of ssl certs and proxies being the first two that come to mind.

I think that an ideal API would be the following:
- allow those to be set per-request
- allow those to be set per-client
- the per-request settings would override the per-client settings

This would cover both the case of 'use same settings for every call' as well as the case 'use a specific setting only for one call'

Alas I don't see how this would be doable without altering teh PSR-7 interfaces (or at least subclassing them in httplug interfaces)

**Comment by dbu** [comment]
sorry, i somehow missed this question. i wrote an answer in #132. in short, our philosophy is that your application should not be bound to http. the layer using http clients should use pre-configured http clients for specific cases. another option could be to have a plugin specific to your client (e.g. guzzle 6) that sets the timeout based on the domain or such logic - its not the job of your business code to know about such shortcomings of the network infrastructure...

i will close this to keep the discussion centralized in one place, if further discussion is needed.

**Comment by zerkms** [comment]
> its not the job of your business code to know about such shortcomings of the network infrastructure

it's not*, but it's still part of the business logic: some applications might be critical to latency hence it would be part of their actual business layer to know how long processes should/may take.

There is even RFC for that: https://www.rfc-editor.org/rfc/rfc7240

**Comment by dbu** [comment]
configure timeouts on the http client.

if you need different settings for different use cases, configure different clients for those use cases and inject the correct client to the correct service.

**Comment by zerkms** [comment]
@dbu any chance you checked https://www.rfc-editor.org/rfc/rfc7240#section-4.3 ? It implies timeouts are configured on per-request basis :shrug:

**Comment by dbu** [comment]
i don't see the RFC implying that. of course the header is sent with each request as all http headers are.

also, the RFC is about the HTTP protocol, not about how to implement clients. 

of course you can do it differently, and i am sure there are valid use cases for this. but if you do something highly specific to HTTP, you will need a specific client implementation (or maybe even raw sockets) to get more control over HTTP.

also be aware that this is the wrong place for this discussion. HTTPlug is only about the async client now. synchronous clients are specified in [PSR-18](https://www.php-fig.org/psr/psr-18/) and the sync client interface in this repository is deprecated. but i don't expect PSR-18 to be changed for dynamic headers either.
