### ISSUE TITLE
Implementation Question: how to code Client options in a library-agnostic way?

### ISSUE THREAD

**Issue by gggeek** [php-http/httplug#132]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no

This is a bit of the same question as in #131, only more generic.

The context is: I am overhauling a venerable library that deals with rpc-over-http calls. In line with current standards and trends, I am splitting the code base in an 'rpc' layer and an underlying 'http' layer, which aims to be conformant to psr-7 and httplug standards. As such, I will also provide an implementation of the psr-7 interfaces, with the goal of allowing at a later time the user of my lib to decide if she would prefer to use another http-transport implementation.

The question I have is: how can I make sure that the parameters that I need to pass to the http client can be defined in an implementation-agnostic way?

The parameters I support at the moment include, f.e.
- call timeout
- ssl certs configuration
- proxy configuration

It seems that neither the psr-7 classes, nor the httplug interfaces account for this in a transportable way.

I have seen that the Client implementations which are part of the core httplug package allow to have options passed in via the constructor, but the constructor signature is different, as well as the naming of the available options (`new Client(MessageFactoryDiscovery::find(), StreamFactoryDiscovery::find(), $options);` for curl vs `new Client($messageFactory, $options);` for socket).

Is there any way to achieve this?

thanks
Gaetano

**Comment by dbu** [comment]
our philosophy is that such http options should be set when creating the client. the class using the client should not need to know about these details, it depends on the target server or environment and other things, which should be the concern of bootstrapping your application. if your client offers the option, even random places doing the rpc calls would need to know about http timeouts and whatnot.

have your client accept a http client in the constructor, and write bootstrap code to set up the your client with a correctly configured client. if you later change the http client implementation, you only need to adjust the bootstrap code.

if you need different configurations, make them explicit by injecting several client instances, e.g. insecureClient (ignores ssl), certificateClient (sends a client ssl cert), slowClient (has an extra long timeout setting). then the client can use the appropriate client for each of its methods. or offer semantic methods, if the client is too generic to know what to use.

**Comment by gggeek** [comment]
Thx @dbu - this makes it more clear to me.

In fact it's funny how much my previous attempt at a 'generic library for rpc style webservices' ( https://github.com/gggeek/ggwebservices ) is similar to HttplugBundle. Maybe I could claim prior art ?

:-P

The only problems I have left are:

1. the library I am upgrading does not have a well defined separation-of-concerns between configuration code and biz-logic code, so upgrading it without introducing BC breaks will be an exercise in creative code (ie. abusing php's open and trustful nature ). But this concern is purely mine...

2. otoh, even if I separate away the http Client constructor and make the rpc layer accept an already-built Client instance, I will still not be able to offer to the end user the possibility to swap out _transparently_ one http-layer implementation for another.
Unless I add to my lib a ClientFactory with a big _switch_ in it, and make the Factory aware of all existing http Clients that support httplug and their constructors. Which is just asking for maintenance failure.
Keep in mind that the goal is *precisely* to allow the user to define in yml configuration all aspects such as proxies and ssl and have her code deal only with the rpc abstraction layer, i.e. have no bootstrap code at all.

**Comment by dbu** [comment]
interesting library! i don't have the time to dig deeply into it now. for 1) maybe do a major version change and some BC breaks to better separate configuration and business logic? for 2) i wonder if the library is doing too much. offering configuration aspects and all might be too much. ez publish is built on top of symfony. your library could allow to specify which httplug client service configured with HttplugBundle should be used for which remote endpoint. you would get rid of having to provide configuring http clients, which is not the core business value of your library... also, letting the user specify their services, you get the power of HttplugBundle plus the total freedom of doing whatever you want in a custom symfony service definition - this likely is more flexible than what your configuration is able to offer, but with no effort from your side to provide and maintain.

i am aware that there are legitimate reasons to have more functionality in one place, to keep things easier to understand. so i don't want to tell you "you are doing it wrong". just food for thought.

i think at this point we are quite sure that we do not want to pass extra request options to the client, to keep configuration and business logic separate. but inputs and feedback how we can improve the code or the documentation are very welcome. (there is even a draft PSR to make the http client a more official specification: https://github.com/php-http/fig-standards/tree/master/proposed/http-client)

**Comment by gggeek** [comment]
I like that draft PSR. Not sure if I can vote on it though, not being part of php core nor php-fig cabal ;-)

I still would like to see a reusable approach to setting up Http Clients, but given the tone of your answer on this point I guess it was already discussed, so I will reserve my lobbying for other occasions.

As for my lib trying to do too much: maybe it is.
In fact the idea is to revamp and extend the existing php-xmlrpc codebase.
The final product is supposed to be modular, self-contained and independent of either eZ or Symfony, but have a Symfony-Bridge Bundle built on top.
And of course achieve world domination.
I currently consider the ggwebservices lib is just a 'beta version' of this plan.

**Comment by dbu** [comment]
PSR-18 has been released
