### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by prolic** [php-http/httplug#134]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | No specific

Do you have any benchmarks of httplug and can tell which adapter is the fastest in terms of performance?

**Comment by Nyholm** [comment]
Not officially no. 
But Joel made some a year ago: https://github.com/joelwurtz/http-client-benchmark

**Comment by prolic** [comment]
Thanks a lot. Feel free to close this issue at wish.
