### ISSUE TITLE
Prepare version 2.0

### ISSUE THREAD

**Issue by Nyholm** [php-http/httplug#139]
I want to release 2.0 in September. At the moment there is no open issues or anything stopping us. We just need to wait for a final release of PSR-18. 

@joelwurtz made [a comment](https://github.com/php-http/httplug/pull/128/files/cbc903aadbe53e2dd39ebc700e6a5aea00b2bc46#r204876337) about async. Is that something we should do before 2.0?

**Comment by joelwurtz** [comment]
Can be done later IMO, not sure i will have time and the future will be to deprecate / remove everything on async as it will only become an implementation problem (no need for a different interface)

**Comment by fbourigault** [comment]
> the future will be to deprecate / remove everything on async as it will only become an implementation problem (no need for a different interface)

Because of Fiber ?

**Comment by joelwurtz** [comment]
Yes by using this php extension https://github.com/concurrent-php/ext-async which i strongly believe that it should be in the core PHP for future version

**Comment by Nyholm** [comment]
Okey. 

I'm ready to release 2.0 now. Lets just wait for the PSR-18 process to be complete.

**Comment by ravage84** [comment]
@Nyholm PSR-18 has been finalized:
https://twitter.com/phpfig/status/1057239369248071680

https://www.php-fig.org/psr/psr-18/

**Comment by Nyholm** [comment]
Wohoo. Great news
