### ISSUE TITLE
Adding deprecated

### ISSUE THREAD

**Issue by joelwurtz** [php-http/httplug#148]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 2.x

Would it make sense to add a deprecation flag everywhere the psr can be used directly ?

**Comment by sagikazarmark** [comment]
I don't think we need to do that, at least not right now. HTTPlug is still widely used, even our own ecosystem. Once we migrated everything to PSR-18 and the community adoption started as well, we can get back to the question of communicating the "deprecation".

**Comment by dbu** [comment]
agree with that - lets wait for a while first, and only then start to fade out the httplug interface.

however, i think it would be a good idea to already now make a note in the readme of version 2 of this that new projects should use/typehint PSR-18 directly, and also note that in the phpdoc of our interface that extends the psr interface.

**Comment by sagikazarmark** [comment]
> however, i think it would be a good idea to already now make a note in the readme of version 2 of this that new projects should use/typehint PSR-18 directly

I did that in a #149

**Comment by dbu** [comment]
shall we keep this issue open or okay to close it?

**Comment by sagikazarmark** [comment]
I think we can't miss the eventual drop of the interface, so I'd say we can close it.
