### ISSUE TITLE
Throwable not supported

### ISSUE THREAD

**Issue by enumag** [php-http/httplug#161]
All the exceptions only accept `\Exception` as `$previous`. They should accept `\Throwable`.

https://github.com/php-http/httplug/blob/master/src/Exception/NetworkException.php#L24

**Comment by GrahamCampbell** [comment]
I think this is correct. A throwable which is not an exception can never cause a network exception. It would indicate an actual mistake in the code.

**Comment by dbu** [comment]
this library supports php versions since 7.0, where Throwable is not available. when we do a new major and have only php versions that have throwable, we could change it, but because of what @GrahamCampbell says, i don't think its very important.

**Comment by enumag** [comment]
> this library supports php versions since 7.0, where Throwable is not available. 

@dbu You're wrong. `\Throwable` was introduced in PHP 7.0.

@GrahamCampbell I said all exceptions. I'm not even using the `NetworkException` one. For instance [`RequestException`](https://github.com/php-http/httplug/blob/master/src/Exception/RequestException.php) as well. The point is that I have a `\Throwable` from my http client and need to call [`Deferred::reject()`](https://github.com/php-http/client-common/blob/ca984d8a60a90473f0bcb425c2bf94f01651729a/src/Deferred.php#L117) which only accepts `ClientExceptionInterface` so I want to wrap my throwable into `RequestException`.

**Comment by xabbuh** [comment]
I think it makes sense to update our exception constructors accordingly.

**Comment by GrahamCampbell** [comment]
I don't think any of the exceptions here should accept a throwable, actually.

**Comment by enumag** [comment]
@GrahamCampbell then please advise me how I should reject the promise when I do get a Throwable.

**Comment by GrahamCampbell** [comment]
Just throw it and crash everything, since if it was not an exception, it's a genuine error in the code, and the correct behaviour then would be to have the error be thrown, just like when a parse error is raised, you have no way to recover.

**Comment by GrahamCampbell** [comment]
I think this issue can be closed?
