### ISSUE TITLE
Remove Interface suffix from interfaces

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#2]
It is commonly believed it is also part of some PSR or recommendation. Actually it is part of the FIG's internal policy.

However I (and thank god, many other people) think it is just wrong to place an implementation detail in object naming conventions. Thus I propose to remove the interface suffix from interfaces.

**Comment by egeloen** [comment]
:+1:

**Comment by egeloen** [comment]
We should remove `Abstract` as well
