### ISSUE TITLE
HttpAdapter don't extend PsrHttpAdapter

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#20]
I wonder if there should be an inheritance between the two interfaces.

**Comment by ddeboer** [comment]
Is the idea that PsrHttpAdapter is a minimal HTTP client implementation and HttpAdapter offers some convenience on top of that? In that case, HttpAdapter could perhaps wrap PsrHttpAdapter.

**Comment by sagikazarmark** [comment]
Yeah, that's the idea. In the original (ivory-http-adapter) package there is a PsrDecorator adapter which does exactly that: accepts a PsrHttpAdapter, but implements HttpAdapter. It has not been migrated, because we haven't finished the interfaces yet.

**Comment by ddeboer** [comment]
I understand. One thing to keep in mind, though, is that other libraries that require an HTTP adapter shouldn’t really have to care whether it’s the basic PsrHttpAdapter or a more convenient HttpAdapter. So that’s one reason to keep the interface inheritance, or have both adapters extend from another base interface.

**Comment by sagikazarmark** [comment]
Well, what I would do is removing inheritance and doing the opposite you are suggesting: have an interface that extends both: HttpAdapter and PsrHttpAdapter.

IMO usually you choose one way to use the HTTP adapter: through the PSR interface or calling regular methods. There can be cases when you need both, in that case you can require an interface which extends both.

The fact that internally every request is converted to a PsrRequest is not relevant here. That's why I think the inheritance should be removed.

I also think that we could probably provide two virtual packages: one for psr-only adapters and one for the other.

But I admit I have various feelings about this one: the method requests in HttpAdapter return Psr Responses. So in fact that interface is also somewhat related to psr.
