### ISSUE TITLE
PSR adapter implementation virtual package

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#21]
Currently we have a virtual package for an adapter implementation. Packages could also provide a psr-adapter-implementation which allows packages to separately provide a PsrHttpAdapter and/or an HttpAdapter.

**Comment by hannesvdvreken** [comment]
They all just provide `php-http/adapter-implementation`, right?

**Comment by sagikazarmark** [comment]
Yeah, and they will. Since we are planning to move the current `HttpAdapter` to `HttpClient`, so that we will only have one adapter interface which removes the confusion: which is provided by this package?

**Comment by sagikazarmark** [comment]
We can probably have a `php-http/client-implementation` virtual package.
