### ISSUE TITLE
Separate interfaces for client, server and networking exceptions

### ISSUE THREAD

**Issue by ddeboer** [php-http/httplug#26]
As discussed in #10.

**Comment by sagikazarmark** [comment]
I have to mention that it is not that easy to differentiate between errors, since each HTTP Clients handle errors differently: some throws exceptions for 4xx status code responses, some don't. Currently we return every response if any, even if 4xx or 5xx responses.

**Comment by ddeboer** [comment]
That’s an option too, at least for requests that return a response. I think you need to throw an exception at least for cases where a networking timeout occurs.

**Comment by sagikazarmark** [comment]
That's true, AFAIK we do it ATM.
