### ISSUE TITLE
Make adapters PSR-7 compliant

### ISSUE THREAD

**Issue by ddeboer** [php-http/httplug#29]
As discussed in https://github.com/php-http/guzzle6-adapter/pull/1: there should only be only one adapter interface and that will take PSR-7 request objects and return PSR-7 response objects. So we need to:
- remove the HttpAdapter
- rename PsrHttpAdapter to HttpAdapter(?)
- create a separate client package that will contain the convenience methods currently in HttpAdapter (`get()`/`post()` etc.).

If we follow this road, are the internal_separation still relevant? Or can we start work on this right away?

**Comment by sagikazarmark** [comment]
It is definitely relevant as it contains some changes that needs to be backported. Also, the separation itself is step one to remove the internal request thing from the adapters.

**Comment by ddeboer** [comment]
Okay, so let’s first get the internal_separation branches merged, and then continue with cleaning up the adapter interfaces.

**Comment by sagikazarmark** [comment]
Yeah.

**Comment by sagikazarmark** [comment]
I am planning to merge those branches by the end of the week.

**Comment by ddeboer** [comment]
Cool! Let me know when you have done that. I’ll write a PR after that to clean up the Adapter interfaces with the Guzzle 6 adapter as a (very simple) testcase.
