### ISSUE TITLE
datas -> data

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#3]
I think using `datas` is incorrect and `data` is the correct form. Actually, `data` is already plural form. So I propose changing it to data everywhere. (Some BC break is also involved)

**Comment by sagikazarmark** [comment]
It is probably an issue that in one of the interfaces there is a `getData($name)` and a `getDatas()` method. I propose to change the first to `getData($name = null)`. When a name is not passed, everything is returned.

**Comment by egeloen** [comment]
I have failed when I have named the property `datas`... :+1: for your proposal! Can you do it in #4?

**Comment by sagikazarmark** [comment]
Are you OK with the function refactoring?

**Comment by egeloen** [comment]
Yes I am :)
