### ISSUE TITLE
Cookie handling

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#35]
@ddeboer mentioned that cookie handling should be possible from adapters.

In the Ivory adapter it was possible by using event dispatcher. I checked the Ivory and the Guzzle CookieJar implementation and they are really similar.

There are two ways to implement cookie handling:
1. If the underlying client supports it pass a cookie option
2. Force the use of an Event adapter which wraps the underlying adapter

Option 2 would be the general solution because not all clients might support cookies. Ultimately the underlying client (like guzzle) would do the same: serialize the cookie jar and place it in the request header.

**Comment by ddeboer** [comment]
In option 2, the event subscriber is a single, generic one for all adapters, isn't it? That means moving the cookie logic from the HTTP client used to the HTTP adapter layer. Sounds reasonable to me: 
1. Generic event subscriber sets cookie header on PSR RequestInterface from php-http CookieJar. 
2. Adapters translate PSR into client-specific request (if necessary) but don't use client-specific cookie handling (such as Guzzle's CookieJar). 
3. Event subscriber reads Set-Cookie header from response and sdds it to the php-http CookieJar.

**Comment by sagikazarmark** [comment]
> In option 2, the event subscriber is a single, generic one for all adapters, isn't it?

Exactly.

> 1, 2, 3

Exactly.

One thing in my mind: Since the PSR-7 messages are immutable, I am not completely sure that an event system is the best idea, because that way the listener would always have to set a message in the event. I am thinking about some sort of middleware system where you pass in the middleware (which plays the role of a listener) and it calls the next middleware in the chain by passing the modified (new) message to the next middleware in the queue.

Not sure how Guzzle does this, since it also have some sort of event system. I am curious if listeners in guzzle always set the new message in the event or use some other logic.

**Comment by ddeboer** [comment]
Agreed, middleware is the way to go. This is [what Guzzle does](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L27), too.

**Comment by sagikazarmark** [comment]
Really? Awesome!

**Comment by sagikazarmark** [comment]
Not sure though if it should work with callables or interfaces.

**Comment by dbu** [comment]
see #37
