### ISSUE TITLE
Base URI handling

### ISSUE THREAD

**Issue by ddeboer** [php-http/httplug#36]
Should we add a `base_uri` option? Alternatively, this could be done with a BaseUriSubscriber, which checks whether request URIs are relative, prefixes them with the base URI (cf. #35).

**Comment by sagikazarmark** [comment]
I am planning to add this feature to the adapter client since there you pass URIs directly to the client. In other adapters it is the developers responsibility to fill the request with valid data. That said, I can imagine a BaseUriSubscriber.

**Comment by dbu** [comment]
would this have to be a plugin? can the client interact with plugins? or would the idea be to have a plugin that completes incomplete urls with a base uri? or can Request objects not be created with incomplete urls?

**Comment by sagikazarmark** [comment]
1. Not have to, but we discussed here why it would be better.
2. Nope, plugins should be transparent
3. Yup
4. Not sure, have to check.

**Comment by dbu** [comment]
if they need to be complete, the base url would make sense in the HttpMethodsClient in the utils.

**Comment by sagikazarmark** [comment]
Agreed. Since HttpMethodsClient is an implementation, we can declare howit should be configured. Options array in constructor with base URL option?

**Comment by joelwurtz** [comment]
And should this populate the Host header of the request if not set ?

**Comment by dbu** [comment]
> how it should be configured. Options array in constructor with base
> URL option?

+1

> And should this populate the Host header of the request if not set ?

base_url should start with protocol and host name imo. you can't send a
request to just a path.

**Comment by sagikazarmark** [comment]
> > And should this populate the Host header of the request if not set ?
> 
> base_url should start with protocol and host name imo. you can't send a
> request to just a path.

Not sure how this answers the original question. AFAIK Host header is not mandatory. I think you can send a request to just a path, if the Host header is populated.

**Comment by dbu** [comment]
oh, true that. well i guess we should also allow to set default headers
that will be merged with the provided headers. and we should leave
validation to the message factory.

i would assume that populating the host header from an absolute url is
also job of the message factory, or of the http handling of the actual
client that opens a network connection. we should be as lazy as we can,
to avoid duplicated logic and weird side effects.
does PSR-7 specify anything about who's responsibility this is?

**Comment by sagikazarmark** [comment]
> i would assume that populating the host header from an absolute url is also job of the message factory,

I disagree. Message Factory should only create the request, but shouldn't validate the input (only the number and format of input parameters).

Actually the client shouldn't validate as well: if someone inputs invalid data and the request fails, an exception should be thrown.

Actually PSR7 has a specification for this header:

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md#host-header

**Comment by dbu** [comment]
> Actually PSR7 has a specification for this header:
> 
> https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md#host-header

great, then we just need to follow this logic. we can add a
preserve_host option with the same semantics to know whether we keep a
default HOST header if the URL contains a host or not. the rest is the
job of the "implementation" as per spec, so that would be the Request class.

**Comment by sagikazarmark** [comment]
Keep in mind, that the interface itself should not care about this. The MethodsClient implementation can. I would say only those adapters should care about this where we know that the underlying client does not.

**Comment by dbu** [comment]
> Keep in mind, that the interface itself should not care about this. The
> MethodsClient implementation can. I would say only those adapters should
> care about this where we know that the underlying client does not.

yeah, totally agree. i thought we are discussing about HttpMethodsClient :-)

the HttpClient interface does not need to repeat what PSR-7 already
defines. but btw, the helpers might also contain some things about this
topic for general cleanup that adapters need to do when the underlying
client does not follow the PSR-7 semantics exactly.

**Comment by joelwurtz** [comment]
In fact Host header is mandatory for 1.1 Protocol but not for 1.0 (i.e. sending a request with 1.1 protocol without the Host header to nginx will result in a 400 bad request)

So maybe this "Plugin" should also throw an Exception if Protocol is 1.1 and attempt to set the Host header fails ?

**Comment by dbu** [comment]
created https://github.com/php-http/utils/issues/11

the rest would now be a topic for the plugins. though i am not sure if the message factory does not take care of that already. might be implementation specific whether the Request instance accepts to be created with incomplete data or not.

**Comment by sagikazarmark** [comment]
Request being incomplete depends on the point of view. For example as @joelwurtz pointed, HTTP 1.1 requires the Host header, 1.0 does not.

**Comment by dbu** [comment]
added note to #37
