### ISSUE TITLE
Documentation Planning

### ISSUE THREAD

**Issue by dbu** [php-http/httplug#46]
This is an issue to discuss fundamental documentation topics.

**Questions**
- where do we keep the documentation source
  1. Separate documentation repository or 
  2. In doc/ folder of this repo
- format
  1. Markdown
  2. reStructured text (with sphinx)?
  3. other?
- hosting
  1. github pages (markdown or rst)
  2. readthedocs.org (sphinx, lots of flexibility)
  3. other?

**Comment by sagikazarmark** [comment]
Ah, actually we already have some sort of documentation: Separate repository in markdown on RTD. I just haven't really made progress.

**Comment by dbu** [comment]
ah, sorry. will open issues in https://github.com/php-http/documentation
