### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#53]
The PHP HTTP client is an abstraction layer to separate general purpose libraries from concrete client implementations in order to make them move flexible. It is the successor of the Ivory HTTP adapter and we should not use Ivory anymore to keep it separate from all the other things under the Ivory name that do unrelated things.

Just calling it "php http" makes it impossible to find this thing in google, as almost website about web development has these keywords. We should have some additional name that makes it findable.

Ideas so far:
- _CPHC/APHC_ for common php http client / abstract php http client by @dbu 
- _Klant_ by @hannesvdvreken 
- _Raspberry_ by @Zarkonnen 
- _Hunlet_ by @patkar 
- _Tupac_ by @greg0ire 
- _Straw_ by @Pierstoval 
- _Httplug_ (and variations) by @sandermarechal
- _Phetch_ by @sandermarechal

**Comment by Zarkonnen** [comment]
"Raspberry", because that's what _phphttp_ sounds like.

**Comment by QuingKhaos** [comment]
Hunlet :dash:

**Comment by greg0ire** [comment]
The Universal Php Abstract Client or ... Tupac. Abstract like a ghost, awaited like the Messiah.

**Comment by sagikazarmark** [comment]
Wow, thanks fo the ideas. I am adding them to the list.

**Comment by sagikazarmark** [comment]
@patkar where does this name come from?

**Comment by QuingKhaos** [comment]
@sagikazarmark Clicked through a crazy name generator ^^

**Comment by sagikazarmark** [comment]
I had the feeling :stuck_out_tongue_winking_eye:

**Comment by Pierstoval** [comment]
Straw, because the client asks for a drink, gets one, but wants a straw. And a straw is thin, sexy, and can gets any drink in any glass.
Edit: no reason, just fun :p

**Comment by hannesvdvreken** [comment]
hahaha that's funny :smile:

**Comment by dbu** [comment]
i love straw. the only worry i have is if it might fit better for an
actual client than an abstraction layer.

**Comment by hannesvdvreken** [comment]
Straw could also be a helper for gulp.

**Comment by Pierstoval** [comment]
@dbu I think this can be debated, because it can be put in this order : Client asks for a Drink, but to be sure that he can drink in any kind of glass/bottle/can, he needs the Straw. 
EDIT: Or we can name it "TinCan" :D 

@hannesvdvreken's right, it could be a Gulp helper (actually I already made a helper for Gulp and named Gryp :laughing: )

**Comment by sandermarechal** [comment]
httplug? phplug? phetch?

**Comment by Pierstoval** [comment]
I like Phetch !

**Comment by dbu** [comment]
httplug! and the logo looks like a power plug world adapter!

**Comment by sagikazarmark** [comment]
:+1: 

BTW naming: should we name the whole organization. Or just the adapter? Or the adapter and other packages, like message-factory?

**Comment by dbu** [comment]
or httphplug but that becomes difficult to say and spell

**Comment by greg0ire** [comment]
phttplug then ?

**Comment by dbu** [comment]
i think i would use the name as sort of a nickname and keep calling the organization php-http. and the client is called httplug or phetch or whatever we chose

**Comment by sagikazarmark** [comment]
:+1:

**Comment by sagikazarmark** [comment]
What about the package vendor? It could also remain php-http OR have a separate vendor for the client related stuff:
- kantphp/klantphp
- httplug/httplug
- php-http/klant
- httplug/guzzle6-adapter

**Comment by sagikazarmark** [comment]
Httplug sounds good, but has no real relation to PHP. Variations with "PHP" in it are a bit complicated I think. Also, the httplug logo idea is great. :+1:

**Comment by joelwurtz** [comment]
Httplug sounds good for me also.

IMO, since the vendor name is php-http, not having some sort of relation to PHP in the name is not a problem

**Comment by dbu** [comment]
i would keep the vendor name php-http and then httplug is specific enough.

**Comment by sagikazarmark** [comment]
I merged the terminology branch and started to remove implementations which are going to be part of the utility repo. The next step is to choose a name. My personal favourites are Klant, Httplug (or a variation) and Phetch. Httplug would be a wise decision with possible logo design keeping in mind. (BTW anyone want to work on that?)

Should we set up some sort of vote? Maybe on Google Docs or in a separate issue?

**Comment by dbu** [comment]
the question is who would be allowed to vote. imo we should try to find something that all with push rights to this repo are happy with. @sagikazarmark as lead should have the final say in this. maybe comments on this issue are enough to decide?

my order of preference is Httplug > Klant > Phetch.

and in my idea, the name would be more of a stick-on thing than deeply integrated. the repository or php namescapce, interfaces or class names would not change.

**Comment by sagikazarmark** [comment]
> my order of preference is Httplug > Klant > Phetch.

Same here

> and in my idea, the name would be more of a stick-on thing than deeply integrated. the repository or php namescapce, interfaces or class names would not change.

Should the namespace remain `Http\Client` then?

Actually I would like everyone to express his/her opinion, but the final decision should be made by @php-http/owners 

So everyone please "vote" this week. If we can't agree on one of the currently proposed names then we postpone the alpha release.

**Comment by dbu** [comment]
> Should the namespace remain |Http\Client| then?

i would say so, yes. i would just say "Httplug, the HTTP client
abstraction for PHP" or something like that. and keep calling the
organisation php-http. httplug is just the name to use and make people
find the thing when searching the web.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by ddeboer** [comment]
> What about the package vendor? It could also remain php-http OR have a separate vendor for the client related stuff

I’d say: one vendor for both to show that the packages play well together. 

> Should the namespace remain `Http\Client` then?

Yes. `Http` is really the core business of all packages in the organisation. 

Currently, I’d vote for Httplug as well.

**Comment by sagikazarmark** [comment]
@hannesvdvreken as the author of name Klant, your situation is not easy. :wink:  What is your opinion about Httplug?

**Comment by hannesvdvreken** [comment]
I'm fine with Httplug as well. Let's vote? Set a time frame and let people comment.

**Comment by sagikazarmark** [comment]
Well, I think we already have a majority favoring Httplug, that's enough for me. The timeframe for voting is this week.

**Comment by hannesvdvreken** [comment]
:+1: httplug it is!

**Comment by dbu** [comment]
> Well, I think we already have a majority favoring Httplug, that's enough
> for me. The timeframe for voting is this week.

i think we have all active owners happy with httplug - so lets go with this!

shall we tweet to ask if somebody wants to design a nice logo?

**Comment by sagikazarmark** [comment]
I will rename the repo and packagist package then.

@dbu Let's go with that tweet

**Comment by sandermarechal** [comment]
Brainfart for a logo, perhaps something where the U in httplug is a stylized electrical plug?

**Comment by sagikazarmark** [comment]
@sandermarechal Yeah, @dbu wanted something similar. He imagined an electrical plug with the Earth maybe?

I am not really a good designer, so I would leave this thing to someone else. :wink:

**Comment by dbu** [comment]
@sagikazarmark but rename to `client`, right? i think the httplug should not be in the php namespace / github repository path. or do you want to go full out with the name?

**Comment by sagikazarmark** [comment]
I planned to rename the repo to httplug, but leave the namespace `Http\Client`.

**Comment by dbu** [comment]
> I planned to rename the repo to httplug, but leave the namespace
> |Http\Client|.

okay, lets do it that way. i wait for you to do that and then ask for
proposals. do we have a twitter name httplug? can you create one?

actually, would be great if you can tweet from that name and we retweet

**Comment by sagikazarmark** [comment]
Will do that. Actually I haven't created an organization name before. Do I have to just register a new account?

**Comment by ddeboer** [comment]
No, you can just create the organisation from your [profile page](https://github.com/settings/organizations).

**Comment by sagikazarmark** [comment]
Thanks :+1: 

Update: @ddeboer I actually meant a Twitter orga account, not a Github one. I've created plenty of Github organizations before. (check my profile :wink: )

**Comment by dbu** [comment]
@ddeboer we are talking about twitter :-) 
@sagikazarmark creating an account with a different email adress is what i did, yes

**Comment by sagikazarmark** [comment]
Yeah, already done it. Retweeted by me.
