### ISSUE TITLE
Virtual packages

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#55]
Currently we have adapter-implementation virtual package which could be renamed to client-implementation, however we now have three interfaces.

Possible virtual packages:
- php-http/psr-client-implementation
- php-http/methods-client-implementation
- php-http/client-implementation

**Comment by dbu** [comment]
i think psr-client-implementation and methods-... are enough. not sure how much sense it makes to combine the two concepts and have one library consume the unified interface.

or we could only have client-implementation and provide two classes in the utils repo that are client-implementation that can be set up with either type of client to add the other part. then you would always use a client that can do both concepts.

**Comment by sagikazarmark** [comment]
The HttpClient exception only exists to ease type-hinting when both the interfaces are needed. I also think that the two are enough for dependency handling.

**Comment by sagikazarmark** [comment]
Is it `php-http/client-implementation` then?

**Comment by dbu** [comment]
:+1:

we mainly need to adjust the existing adapters and the doc for this, right?

**Comment by sagikazarmark** [comment]
Yes.

**Comment by sagikazarmark** [comment]
`php-http/client-implementation`
