### ISSUE TITLE
Utility package

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#56]
Currently there are a few things in the package which are not really part of the contract:
- Body implementations
- BatchRequest trait
- Plugin to convert HTTP Error responses to exceptions (and the HttpErrorException class)

The plan is to move them to a utility package.

**Comment by joelwurtz** [comment]
We could also provide some Stream Implementation (but maybe not in the Utility package)

Some stream implementation that i can think of and have not seen in current psr7 implementations (guzzle / diactoros) : 
- ChunkStream : To use with the Transfer Encoding chunked header / value
- DeflateStream : To use with the Transfer Encoding deflate header / value

**Comment by sagikazarmark** [comment]
We definitely could have those in a separate package. However Guzzle has  a quite good collection of streams, I would probably try to send PRs there first.

**Comment by dbu** [comment]
:+1:

**Comment by dbu** [comment]
i edited the description for the error => exception part.

**Comment by sagikazarmark** [comment]
> and the HttpException class

?

The HttpException should be part of the contract. I guess you mean the non-existent HttpErrorException.

**Comment by dbu** [comment]
sorry, yes. fixed.

**Comment by sagikazarmark** [comment]
Also, we haven't discussed where plugins should exactly go: separate repo each? one repo? There is a plugin issue opened where other possible plugins are listed.

**Comment by dbu** [comment]
plugins in the utility repo sounds fine to me. keep the number of repos
in check. in the end, almost all projects probably will use the utility
repo. but still it keeps the contact simple and clean, making it worth.

**Comment by dbu** [comment]
this is now a thing: https://github.com/php-http/utils
