### ISSUE TITLE
naming of the virtual package

### ISSUE THREAD

**Issue by dbu** [php-http/httplug#68]
we currently say that adapters must provide php-http/adapter-implementation.

this should become php-http/httplug-implementation, right?

**Comment by sagikazarmark** [comment]
Nope, we discussed somewhere that it should be psr-client-implementation and methods-client-implementation

**Comment by dbu** [comment]
that is fine as well. the documentation is outdated then...

**Comment by sagikazarmark** [comment]
Indeed it is

**Comment by dbu** [comment]
we should decide this soon as it is one important step to make alpha usage possibile. its a blocker for https://github.com/dbu/HttplugBundle/issues/8 for example.

so your suggestion is php-http/psr-client-implementation ? and php-http/methods-client-implementation for the convenience client with request factory built in? i am fine with that.

**Comment by dbu** [comment]
though with the HttpMethods trait i wonder if it makes sense to allow two kinds of client. i am afraid of the additional complexity and confusion this can cause. maybe we should declare the Psr and Method interfaces as not intended to be implemented standalone? and only have a single php-http/client-implementation?

just one example: what should the interface the httplug.client service promise? or should we have 2 services for the two kind of clients? if we want to keep the client with message-factory built in, i think we have to make it a mandatory part of every client.

**Comment by sagikazarmark** [comment]
Duplicate of #55?

**Comment by dbu** [comment]
yup, sorry
