### ISSUE TITLE
Contributor Code of Conduct

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#70]
I know the Contributor Code of Conduct from [FuelPHP](http://fuelphp.com/). It was part of my general boilerplate, but I removed it for some reasons. In the last few months I was thinking about adding it back, but @philsturgeon gave me the last push by adding it to the League skeleton repo.

So I decided to add it to this project. It is a good guide next to our technical one.

**Comment by philsturgeon** [comment]
Thanks for the ping. Hey your website listed here doesn't work :)

**Comment by sagikazarmark** [comment]
Unfortunately @egeloen still didn't add me as an administrator to the domain, so I couldn't set it up. We are planning to release an alpha very soon, it would be good to set a website up.

**Comment by dbu** [comment]
i merged the CoC in #59 - thanks for the initiative, fully agree on this!

**Comment by sagikazarmark** [comment]
:+1:
