### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#71]
Hey guys,

I have been thinking about if we could improve the communication. Github issues are awesome, but we could do better. Since this is the first time for me to be part of such a large group (I usually did things alone so far), I only have a few guesses how it could be done in an organized way. If any of you have better ideas, I am open to them.

So we have github issues. Great, but sometimes direct communication would be better.

We have a gitter room, but let's admit: noone really wants to use yet another communication channel.

I was thinking about slack. In theory, it can be made public as well using slackin.

Other possibilities: email, skype, twitter.

So what do you think guys? What do you use at FOS/Made with Love?

**Comment by hannesvdvreken** [comment]
I'm ok with Gitter though. At madewithlove we use slack, but I don't mind using Gitter. It keeps an archive and sends email notifications if you are mentioned. What do you need more?

**Comment by sagikazarmark** [comment]
Just a few thoughts:
- Gitter application is slow (at least for me)
- Notifications are also slow (not just the email ones: even if the tab is open, when not active, I just don't get the notifications right away)
- Slack is open anyway (for me as well, we use it at work too): and keeping it in mind: why would we use two communication channels?

**Comment by joelwurtz** [comment]
If you want me in, i also use slack so this is painless for me

**Comment by sagikazarmark** [comment]
Slack channel created.
