### ISSUE TITLE
Supporting php7

### ISSUE THREAD

**Issue by joelwurtz** [php-http/httplug#72]
With the upcoming release of php7 all libraries under php-http should support php7 IMO, WDYT ?

(The change will be to remove php7 from the allow_failure in travis file in all libraries)

**Comment by hannesvdvreken** [comment]
As long as PHP 7 is not released, allowing failures on it allows us to not worry about it when it fails because of a breaking change in the consecutive builds of PHP 7 or release candidates.

When PHP 7 is released, it is indeed recommended to remove it from the allow_failures.

**Comment by dbu** [comment]
PHP 7 is in RC state. which means i would not expect much to happen that could affect us here. and if it does we should report it to the PHP 7 maintainers so they can fix it. 

 I am +1 on the proposal.

Also, seeing that currently the build fails, we really should work on fixing the build for 7. There might be some issue that would lead to a BC break for us to be able to fix it (like doctrine has a problem with the class called `String` as PHP 7 says this is a reserved word, and they have a class for annotations for that...).

@joelwurtz could you work on fixing the PHP 7 build? we can then still decide whether we allow failures or not - but the stuff that is failing now is likely to keep failing. Maybe its just the phpspec version we use https://travis-ci.org/php-http/httplug/jobs/86556672

**Comment by joelwurtz** [comment]
I think the current break stuff in PHP7 comes more from phpspec than this library (see https://travis-ci.org/phpspec/phpspec/phpspec/jobs/87006391)

**Comment by sagikazarmark** [comment]
@joelwurtz you are right, failing is because phpspec. AFAIK phpspec guys already work on a fix.
