### ISSUE TITLE
Tag alpha

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#76]
Are there any more blockers before tagging alpha?

Even if documentation is not completely ready, if everyone is happy with the current state, we should freeze and tag it. We can move forward with documentation. Those, who want to play with it, can do it without documentation, as the code itself is documented enough in docblocks (I think).

**Comment by dbu** [comment]
only thing i can think of is to adjust utils to #75 (delete stuff)

but utils is not critical anymore, so lets go ahead.

**Comment by sagikazarmark** [comment]
Yeah, utils is just extra stuff. I don't think it should affect the progress of the contract.
