### ISSUE TITLE
Rename HttpAsyncClient to AsyncHttpClient

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug#84]
Name seems to be more logical this way.

Ping @joelwurtz @dbu

**Comment by sagikazarmark** [comment]
On the other hand many things rely on it already, but if we want to change it, we should do it now.

**Comment by joelwurtz** [comment]
really don't mind, both seems ok to me so a +0 for me

**Comment by sagikazarmark** [comment]
Ok, we sticked to HttpPsrClient and HttpMethodsClient earlier anyway, so we can leave it as is.

**Comment by dbu** [comment]
agreed. lets leave it as is. its just a name ;-)
