### ISSUE TITLE
Mock client

### ISSUE THREAD

**Issue by ddeboer** [php-http/httplug#89]
Goal: a lightweight client that can act as a test double, inspired by the [one in FOSHttpCache](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/6a3f996f43cdddabd60b4dc02541e49748f2aa09/src/Test/HttpClient/MockHttpAdapter.php#L19-L19).
1. Where should it go? We currently have php-http/mock-adapter and php-http/utils.
2. How will we return responses? 
   - Depend on discovery to instantiate a response or create a separate `MockResponse`? The latter may be a lot of work, though, because `ResponseInterface` includes the `with…()` change methods. 
   - Alternatively, only have the MockClient return responses that have been set beforehand (so no default 200 response).

**Comment by sagikazarmark** [comment]
Well, we discussed to have it in the utils repo IIRC.

**Comment by ddeboer** [comment]
Correct, but if we need more classes than just the MockClient, we may want them in a separate repo.

**Comment by sagikazarmark** [comment]
Like the discovery and message factory?

**Comment by ddeboer** [comment]
Yeah, I should’ve said: if we start introducing more deps into the utils package. It’s probably best to decide on where to place the MockClient after we have discussed the response generation.

**Comment by sagikazarmark** [comment]
Hm, you are right. Should it be a generic test repo, like test-utils, or mock-client?

**Comment by sagikazarmark** [comment]
For me requests/responses are kind of ValueObjects, so not sure mocking them is the right way.

**Comment by dbu** [comment]
the client itself should not need to generate responses. the testing
framework should pre-set the responses on the client. i would not try to
mock messages, they are well tested value objects (if there are problems
with those classes, you really want to know, even if its technically the
wrong place to find the bugs)

**Comment by sagikazarmark** [comment]
I am thinking about making the adapter-integration-tests repo into a generic test repo with tests for clients and the mock client. WDYT?

**Comment by dbu** [comment]
i think as with the utils, we have two separate target audiences: 
- _implementors_ of a client/adapter that need to test their conformity to the Httplug standard 
- library/project implementors that need to unit test a class _using_ Httplug

i think the two purposes are very different and we should keep them in separate repositories.

**Comment by sagikazarmark** [comment]
ok, so test-utils then?

**Comment by dbu** [comment]
yep, that would be consistent with utils. and client-integration-tests
for HTTPlug conformance?

**Comment by sagikazarmark** [comment]
:+1:

**Comment by ddeboer** [comment]
We decided to deprecate php-http/utils (in favour of client-utils). As I agree we shouldn’t add the mock to client-integration-tests (as that serves a different audience), I added the mock client to [its own package](https://github.com/php-http/mock-adapter/pull/1) for now.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by ddeboer** [comment]
Now available at https://github.com/php-http/mock-client.
