### ISSUE TITLE
Namespace of all packages

### ISSUE THREAD

**Issue by joelwurtz** [php-http/httplug#98]
I would like to propose the following namespace for our different package (goal is to have, in the future, possibility to assemble all package into a single one with subsplit):
- Httplug : `Http\Client` (not changed)
- Promise : `Http\Promise` (not changed)
- Message-Factory: `Http\Message` (not changed)
- Tools : `Http\Tools` (`Http\Client\Tools` actually)
- Utils : `Http\Utils` (Http\Client\Utils actually)
- Plugin : `Http\Plugin` (Http\Client\Plugin actually)
- Adapters (guzzle / react / ...) : `Http\Adapters\[Adapter Name]`, so Guzzle6 will have this namespace for example : `Http\Adapters\Guzzle6` (instead of `Http\Adapter` actually)
- Clients (socket / curl / ...) : `Http\Clients\[Client Name]`, so Socket will have `Http\Clients\Socket`
- Discovery : `Http\Discovery` (not changed)

WDYT ?

**Comment by sagikazarmark** [comment]
Looks good to me.

One comment: Plugin seems to be a bit inconsistent with the other namespaces, which are mostly plural (in case of a collection instead of one, separated component).

**Comment by joelwurtz** [comment]
So Http\Plugins then ?

**Comment by sagikazarmark** [comment]
Sounds logical to me :smile:

**Comment by joelwurtz** [comment]
pinging client / adapters maintainers since it concerns them a lot @mekras @shulard @Nyholm @ddeboer WDYT ?

**Comment by dbu** [comment]
:+1:

**Comment by shulard** [comment]
Hello!

For me your proposal is a lot cleaner than the actual one! :+1:

**Comment by jeromegamez** [comment]
I spent hours writing this comment, so it might be that some of my thoughts got mingled. If you take something out of this, let it be two things: we have too many repos, and these are really nicely formatted tables :D.

## Overview of current repos

| Repo | Description | Namespace | Scope |
| --- | --- | --- | --- |
| [`authentication`](https://github.com/php-http/authentication) | Authenticate PSR-7 requests | `Http\Authentication` | Message |
| [`client-tools`](https://github.com/php-http/client-tools) | Tools for HTTPlug client implementors | `Http\Client\Tools` | Client |
| [`cookie`](https://github.com/php-http/cookie) | Simple Cookie container logic for HTTP Requests | `Http\Cookie` | Message |
| [`curl-client`](https://github.com/php-http/curl-client) | cURL client | `Http\Curl` | Client |
| [`discovery`](https://github.com/php-http/discovery) | Finds installed adapters and message factories | `Http\Discovery` | Adapter/Message |
| [`encoding`](https://github.com/php-http/encoding) | PSR 7 Stream for transfer / content encoding headers (chunked, deflate, compress, ...) | `Http\Encoding` | Message |
| [`guzzle5-adapter`](https://github.com/php-http/guzzle5-adapter) | Guzzle 5 HTTP adapter | `Http\Adapter` | Adapter |
| [`guzzle6-adapter`](https://github.com/php-http/guzzle6-adapter) | Guzzle 6 HTTP adapter | `Http\Adapter` | Adapter |
| [`helper`](https://github.com/php-http/helper) | Helper classes for HTTP related data | `Http\Helper` | Message |
| [`httplug`](https://github.com/php-http/httplug) | HTTPlug, the HTTP client abstraction for PHP | `Http\Client` | Client |
| [`message-decorator`](https://github.com/php-http/message-decorator) | Decorators for PSR-7 HTTP Messages | `Http\Message` | Message |
| [`message-factory`](https://github.com/php-http/message-factory) | Factory interfaces for PSR-7 HTTP Message | `Http\Message` | Message |
| [`mock-adapter`](https://github.com/php-http/mock-adapter) | Mock HTTP Adapter for testing | `Http\Adapter` | Adapter |
| [`plugins`](https://github.com/php-http/plugins) | Plugin client, decorate http client with middlewares | `Http\Client\Plugin` | Client/Message |
| [`promise`](https://github.com/php-http/promise) | Promise used for asynchronous HTTP requests | `Http\Promise` | message |
| [`psr7-vcr`](https://github.com/php-http/psr7-vcr) | Not even started yet (mea culpa :)) | (none) | Client |
| [`react-adapter`](https://github.com/php-http/react-adapter) | (no description) | `Http\Adapter` | Adapter |
| [`socket-client`](https://github.com/php-http/socket-client) | Socket client | `Http\Socket` | Client |
| [`utils`](https://github.com/php-http/utils) | HTTP Client Utilities | `Http\Client\Utils` | Client/Message |

## Suggested changes

With this categorization in mind, I would like to suggest the following changes.

Overall: From [php-http/utils](https://github.com/php-http/utils), I would use just one message factory, either zend-diactoros or guzzle/psr7 - any PSR-7 compliant HTTP Client should be able to work with either of these. Both have no special dependencies, so this should just be a matter of decision.

### Message-related repos

Suggestion: Merge all repos into one, e.g. `php-http/message`.

Reasoning: It could of course be that I want to create messages with the factory, but I don't need authentication or a special stream, but the single components don't disturb each other. At the moment, if I wanted to create an authenticated HTTP Message with Cookies, I would have to require

| Repo(s) | Current Namespace(s) | New Namespace |
| --- | --- | --- |
| [`authentication`](https://github.com/php-http/authentication) | `Http\Authentication` | `Http\Message\Request\Authentication` |
| [`cookie`](https://github.com/php-http/cookie) | `Http\Cookie` | `Http\Message\Request\Cookie` |
| [`encoding`](https://github.com/php-http/encoding) | `Http\Encoding` | `Http\Message\Stream` |
| [`helper`](https://github.com/php-http/helper) | `Http\Helper` | `Http\Message\Helper`<br/>`Http\Message\Helper\Extractor`<br/>`Http\Message\Helper\Normalizer`<br/>`Http\Message\Helper\Parser` |
| [`message-decorator`](https://github.com/php-http/message-decorator)<br/>[`message-factory`](https://github.com/php-http/message-factory)<br/>[`utils`](https://github.com/php-http/utils)(parts) | `Http\Message` | `Http\Message\Factory`<br/>`Http\Message\Factory\Decorator`<br/>`Http\Message\Factory\MessageFactory`<br/>`Http\Message\Factory\StreamFactory`<br/>`Http\Message\Factory\UriFactory` |
| [`promise`](https://github.com/php-http/promise)<br/>[`client-tools`](https://github.com/php-http/client-tools)(parts) | `Http\Promise` | `Http\Message\Promise`<br/>`Http\Message\Promise\FulfilledPromise`<br/>`Http\Message\Promise\RejectedPromise` |

### Client-related Repos

| Repo | Current Namespace | New Namespace |
| --- | --- | --- |
| [`httplug`](https://github.com/php-http/httplug) | `Http\Client` | `Http\Client` |
| `batch-client` (extracted from [`utils`](https://github.com/php-http/utils)) | N/A | `Http\Client`<br/>`Http\Client\BatchClient` (class) |
| [`client-tools`](https://github.com/php-http/client-tools) | `Http\Client` | `Http\Client\Tools` |
| [`curl-client`](https://github.com/php-http/curl-client) | `Http\Curl` | `Http\Client`<br/>`Http\Client\CurlClient` (class)<br/>(shouldn't this be an adapter?) |
| [`plugins`](https://github.com/php-http/plugins) | `Http\Client\Plugin` | `Http\Client\Plugin` |
| [`socket-client`](https://github.com/php-http/socket-client) | `Http\Socket` | `Http\Client`<br/>`Http\Client\SocketClient` (class)<br/>(shouldn't this be an adapter?) |
| `vcr-client`/[`psr7-vcr`](https://github.com/php-http/psr7-vcr) | N/A | `Http\Client`<br/>`Http\Client\VcrClient` (class) |

### Adapter-related repos

| Repo | Current Namespace | New Namespace |
| --- | --- | --- |
| `curl-adapter`? | N/A | `Http\Adapter\Curl` |
| [`guzzle5-adapter`](https://github.com/php-http/guzzle5-adapter) | `Http\Adapter` | `Http\Adapter\Guzzle5` |
| [`guzzle6-adapter`](https://github.com/php-http/guzzle6-adapter) | `Http\Adapter` | `Http\Adapter\Guzzle6` |
| [`mock-adapter`](https://github.com/php-http/mock-adapter) | `Http\Adapter` | `Http\Adapter\Mock` |
| [`react-adapter`](https://github.com/php-http/react-adapter) | `Http\Adapter` | `Http\Adapter\React` |
| `socket-adapter`? | N/A | `Http\Adapter\Socket` |

**Comment by sagikazarmark** [comment]
Wow @jeromegamez I cannot find words to describe this. :smile: :+1: 

The fact that we have too many packages came up a few times already. There are upsides and downsides of both the single repo and the multi repo solution.

> but the single components don't disturb each other.

This is true, but I would at least partially modify this statement: I would exclude contracts and limit to implementations.

Contracts are probably better to keep somewhat separated so that you can require them without implementations, which is useful when you want to implement your custom stuff.

> I would use just one message factory, either zend-diactoros or guzzle/psr7

I am not sure I understand this. Should we support only one? That's not really interoperable.

> shouldn't this be an adapter?

Well, as you originally proposed in April when we started the whole thing, we are actually working on an HTTP Client abstraction, not an apdater one. So when we implement something new, then it is actually a client. When we implement a wrapper something already existing, then it's an adapter.

To tell the truth, the most useful proposal from your comment is the message thing for me. Message related stuff is really spread across many repositories. With the following modifications, I think that we should actually start working on php-http/message:
1. Promise is not message related. The plan is to replace it with a PSR (when it comes to reality). Although promise implementations from client-tools might be moved to the promise repository.
2. I think message factory is something that we probably want to keep separated. It should be used together with psr/http-message, so that you can provide factories with your implementation. I wasn't thinking so far that message factories should be standardized, but the more I am thinking about the more I think they should be. The fact that we have these message factories not next to the messages themselves makes me itchy.

Honestly, we really have many components which can be categorized from this point of view (used with messages) and I haven't thought about them before. Good idea @jeromegamez

**Comment by xabbuh** [comment]
I would to always use singular instead of plural (so Plugin and Adapter instead of Plugins and Adapters).Utils is the only namespace I would keep in plural.

**Comment by sagikazarmark** [comment]
Not sure if we should merge encoding into a message package as it relies on guzzle psr7.

**Comment by jeromegamez** [comment]
Sorry, I'm writing from my mobile, so please excuse my brevity :)

I don't think relying on guzzle/psr7 is a bad thing - it's a lib without dependencies and could be easily exchanged if someday something "better" comes up.

For me it's the same argument as with the message factory: we have the psr/http-message specification, and as long as the generated messages/streams are PSR-7 compliant, it shouldn't matter which lib we use to create them - each client/adapter can handle PSR-7 compliant Message-/Stream-Objects. If they are created by guzzle/psr7 or zend-diactoros or any other factory, shouldn't matter in the end. Please tell me if I'm wrong!

**Comment by sagikazarmark** [comment]
Here is an argument:

https://github.com/satooshi/php-coveralls/issues/80#issuecomment-165829065

I think it is the basic idea behind adapters, and should be for messages as well that you can use your own. So if you already use something in your project, why would you need to install another?

**Comment by jeromegamez** [comment]
Good point

**Comment by dbu** [comment]
@xabbuh can you explain why you would use singular? it feels ok to me and would require less changes, which is a plus. but are there specific reasons for it?

**Comment by xabbuh** [comment]
If the namespace were plural, I would expect each and every class from that namespace to a plugin, an Adapter and so on. While this might be true for Adapters right now a plugin usually contains lots more classes than just a single entry point class.

**Comment by ddeboer** [comment]
> I would expect each and every class from that namespace to a plugin, an Adapter and so on. While this might be true for Adapters right now

Not quite: the guzzle6-adapter already contains an extra class: the wrapper (adapter?) around Guzzle promises. The fact that we (sometimes) have multiple classes per adapter makes me agree with @joelwurtz’s proposal to have a namespace per adapter, but I prefer singular too, so: `Http\Adapter\Guzzle6Adapter`.

Re the amount of packages: I’m not too happy with the tools and utils names; what, exactly, is the difference between the two?

**Comment by xabbuh** [comment]
> Not quite: the guzzle6-adapter already contains an extra class: the wrapper (adapter?) around Guzzle promises.

Well, this then supports my reasoning for using a singular `Adapter` namespace even more. :)

**Comment by sagikazarmark** [comment]
> Re the amount of packages: I’m not too happy with the tools and utils names; what, exactly, is the difference between the two?

Actually it is under discussion to merge the two under a better name: php-http/httplug#99

The difference between them: Utils holds utilities for reusable library implementors, class-tools holds utilities for client implementors.

**Comment by sagikazarmark** [comment]
Okay, based on community feedback, it seems that singular namespace names are more welcome. Based on this and #99 I would like to summarize the current package reorganization plan:

authentication + message-factory-implementations + message-decorator + encoding = message
utils + client-tools = client-common

Namespaces:

`Http\Client` for HTTPlug and Client implementations: curl, socket, mock
`Http\Adapter` for adapters: Guzzle 5,6, React
`Http\Message` for message-factory contract and php-http/message
`Http\Client\Common` for common client stuff: batch client, methods client, client decorators and emulators (merged utils and client-tools)

Did I mis(understood) something?

(Not as nice as @jeromegamez's :wink: )

**Comment by jeromegamez** [comment]
I like it! :+1:

**Comment by joelwurtz** [comment]
Some questions left : 
- Should we have a subnamespace for each adapter / client implementation : `Http\Adapter\Guzzle5` / `Http\Adapter\Guzzle6` / ... ?
- Where does Plugin stand in all this namespace ?

**Comment by dbu** [comment]
+1 for the subnamespaces.

**Comment by sagikazarmark** [comment]
What should the client classes be named in this case?

`Http\Adapter\Guzzle6\Client`
`Http\Adapter\Guzzle6\GuzzleClient`

`Http\Adapter\Guzzle6\Promise`

**Comment by dbu** [comment]
> Http\Adapter\Guzzle6\Client
> +1
> Http\Adapter\Guzzle6\GuzzleClient
> -1
> Http\Adapter\Guzzle6\Promise
> +1

**Comment by sagikazarmark** [comment]
Well, same class name would actually make things easier when you just replace the implementation with another: rewrite the namespace import, but don't change the code.

**Comment by dbu** [comment]
how do you mean? if i got this correctly i am -1: if things depend on order of autoload or explode if for some reason i have more than one client/adapter in my project (e g partial migration) this is not nice. and its vety implicit

**Comment by xabbuh** [comment]
I think what @sagikazarmark means is that in the following code I would maybe just have to replace `use Http\Adapter\Guzzle6\Client` with `use Http\Adapter\Buzz\Client` when I want to switch the implementation being used in my project:

``` php
use Http\Adapter\Guzzle6\Client;

$client = new Client(...);

// ...
```

**Comment by sagikazarmark** [comment]
@xabbuh exactly.

**Comment by xabbuh** [comment]
By the way, I don't think that this is really relevant (constructor arguments can differ or people just use a DI container). However, I like `Client` as the name as it is short, self-explanatory and it will be consistent throughout the different implementations.

**Comment by ddeboer** [comment]
The only annoying thing with `Http\Adapter\Guzzle6\Client` is that `Client` is more common in projects than `Guzzle6Client` so IDE auto-completion will not work as well. Still, I prefer the simple `Client` for the reasons that @xabbuh mentions.

**Comment by sagikazarmark** [comment]
@xabbuh We usually try to achieve to allow using adapters with zero-config. In that case it might be useful.

@ddeboer it depends on the IDE. For example PHPStorm is smart enough to mitigate this problem.

**Comment by xabbuh** [comment]
@sagikazarmark Cool! That's even better then.

**Comment by dbu** [comment]
ah, got it. yeah Client as class name is fine. people not liking that can
always alias to something else in the use statemenz.

**Comment by ddeboer** [comment]
Implemented the new namespace setup in our [Guzzle6 adapter](https://github.com/php-http/guzzle6-adapter/pull/25). Last thing that needs to be decided for the adapters is whether the class name should be `Client` or `Adapter`, as discussed [on the PR](https://github.com/php-http/guzzle6-adapter/pull/25#discussion-diff-48531589).

**Comment by sagikazarmark** [comment]
Ideas:
- Http\Adapter\Guzzle6\Client
- Http\Adapter\Guzzle6\Adapter
- Http\Guzzle6Adapter\Client

**Comment by dbu** [comment]
the issue says namespace, but we talk about the FQN here, right?

my vote goes for `Http\Guzzle6Adapter\Client` but i can live with all of
them. having adapter in the namespace and client as class name seems a
good idea to me.

**Comment by sagikazarmark** [comment]
> the issue says namespace, but we talk about the FQN here, right?

Yeah, this discussion is kinda for everything now.

So namespaceing then (and FQCNs):

Adapters: `Http\SomeAdapter\Client`
Clients: `Http\SomeClient\Client`

**Comment by dbu** [comment]
+1

**Comment by xabbuh** [comment]
I would prefer a schema that follows `Http\Adapter\<name>\Client`.

**Comment by sagikazarmark** [comment]
`Http\Adapter\Guzzle6\Client` or `Http\Adapter\Guzzle6Adapter\Client`

Too long and the second is redundant. Why do you prefer this version?

**Comment by dbu** [comment]
Http\Adapter\Guzzle6\Client looks good to me too. agree that Http\Adapter\Guzzle6Adapter\Client would be redundant.

**Comment by xabbuh** [comment]
@sagikazarmark I meant the former one (the latter is indeed redundant). This way all adapters will be under a common namespace.

**Comment by ddeboer** [comment]
@sagikazarmark I’m fine with `Http\Adapter\Guzzle6\Client`, too. Do you have any objections to it? The only problem I see is the one mentioned [here](https://github.com/php-http/guzzle6-adapter/pull/25/files#r48531589): usually external clients (such as Guzzle) have a class called `Client`, which may cause some confusion with our adapter’s (HTTPlug) `Client` class. However, I don’t really mind doing:

``` php
use GuzzleHttp\Client as GuzzleClient;
use Http\Adapter\Guzzle6\Client;

$guzzleClient = new GuzzleClient(…);
$httplugClient = new Client($guzzle);
```

**Comment by sagikazarmark** [comment]
Fine by me as well.

**Comment by dbu** [comment]
i would do this to be explicit:

```
use GuzzleHttp\Client as GuzzleClient;
use Http\Adapter\Guzzle6\Client as GuzzleAdapter;

```

**Comment by sagikazarmark** [comment]
I think this is resolved, isn't it?

**Comment by ddeboer** [comment]
Yes.

**Comment by joelwurtz** [comment]
I think react and curl adpater / client need to change their namespace, but maybe better to do an issue directly on the repository.

**Comment by sagikazarmark** [comment]
You are right. Issues are opened.
